
# SEO settings
title: "Yes"
title2: ",丁小江" # default: ""
description: "丁小江自由发挥空间."
keywords: "丁小江, Jekyll, SEO, blog, web"
url: http://1024b.github.io # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo:
disqus_shortname: ""
twitter_username: ""
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "丁小江(Ryan)"
  job      : "Web Software Engineer"
  bio      : ""
  thumb    : /images/author.jpg
  email    : ddinnnng@qq.com
  url      : http://1024b.github.io
  github   : https://github.com/1024b
  twitter  :
  facebook :
  linkedin :

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
